/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  auth_dept: () => import("@/views/auth/dept/index.vue"),
  auth_menu: () => import("@/views/auth/menu/index.vue"),
  auth_resource: () => import("@/views/auth/resource/index.vue"),
  auth_role: () => import("@/views/auth/role/index.vue"),
  auth_user: () => import("@/views/auth/user/index.vue"),
  home: () => import("@/views/home/index.vue"),
  message: () => import("@/views/message/index.vue"),
  monitor_alert: () => import("@/views/monitor/alert/index.vue"),
  monitor_gateway: () => import("@/views/monitor/gateway/index.vue"),
  monitor_log: () => import("@/views/monitor/log/index.vue"),
  monitor_online: () => import("@/views/monitor/online/index.vue"),
  monitor_overview: () => import("@/views/monitor/overview/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_dict: () => import("@/views/system/dict/index.vue"),
  system_file: () => import("@/views/system/file/index.vue"),
  system_notice: () => import("@/views/system/notice/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
