/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 11
    }
  },
  {
    name: 'auth',
    path: '/auth',
    component: 'layout.base',
    meta: {
      title: 'auth',
      i18nKey: 'route.auth',
      icon: 'mdi:shield-account-outline',
      order: 8,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'auth_dept',
        path: '/auth/dept',
        component: 'view.auth_dept',
        meta: {
          title: 'auth_dept',
          i18nKey: 'route.auth_dept',
          icon: 'mdi:account-multiple-outline',
          order: 2,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'auth_menu',
        path: '/auth/menu',
        component: 'view.auth_menu',
        meta: {
          title: 'auth_menu',
          i18nKey: 'route.auth_menu',
          icon: 'material-symbols:route',
          order: 4,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'auth_resource',
        path: '/auth/resource',
        component: 'view.auth_resource',
        meta: {
          title: 'auth_resource',
          i18nKey: 'route.auth_resource',
          icon: 'mdi:api',
          order: 5,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'auth_role',
        path: '/auth/role',
        component: 'view.auth_role',
        meta: {
          title: 'auth_role',
          i18nKey: 'route.auth_role',
          icon: 'carbon:user-role',
          order: 3,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'auth_user',
        path: '/auth/user',
        component: 'view.auth_user',
        meta: {
          title: 'auth_user',
          i18nKey: 'route.auth_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'message',
    path: '/message',
    component: 'layout.base$view.message',
    meta: {
      title: 'message',
      i18nKey: 'route.message',
      icon: 'mdi:message-badge-outline',
      order: 2,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor',
      icon: 'mdi:monitor-dashboard',
      order: 10,
      roles: ['R_SUPER']
    },
    children: [
      {
        name: 'monitor_alert',
        path: '/monitor/alert',
        component: 'view.monitor_alert',
        meta: {
          title: 'monitor_alert',
          i18nKey: 'route.monitor_alert',
          icon: 'mdi:bell-alert-outline',
          order: 4,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'monitor_gateway',
        path: '/monitor/gateway',
        component: 'view.monitor_gateway',
        meta: {
          title: 'monitor_gateway',
          i18nKey: 'route.monitor_gateway',
          icon: 'mdi:transit-connection-variant',
          order: 3,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'monitor_log',
        path: '/monitor/log',
        component: 'view.monitor_log',
        meta: {
          title: 'monitor_log',
          i18nKey: 'route.monitor_log',
          icon: 'mdi:file-document-multiple-outline',
          order: 5,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online',
          icon: 'mdi:monitor-account',
          order: 6,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'monitor_overview',
        path: '/monitor/overview',
        component: 'view.monitor_overview',
        meta: {
          title: 'monitor_overview',
          i18nKey: 'route.monitor_overview',
          icon: 'mdi:view-dashboard-outline',
          order: 1,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog-outline',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config',
          icon: 'mdi:tune-variant',
          order: 1,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict',
          icon: 'mdi:bookshelf',
          order: 2,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'system_file',
        path: '/system/file',
        component: 'view.system_file',
        meta: {
          title: 'system_file',
          i18nKey: 'route.system_file',
          icon: 'mdi:folder-file-outline',
          order: 4,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice',
          icon: 'mdi:bullhorn-outline',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
