<script setup lang="tsx">
import { computed, nextTick, ref, watch } from "vue";
import type { SelectOption } from "naive-ui";
import { menuIconTypeOptions, menuTypeOptions } from "@/constants/business";

import { addMenu, updateMenu } from "@/service/api";
import { useFormRules, useNaiveForm } from "@/hooks/common/form";
import { getLocalIcons } from "@/utils/icon";
import { $t } from "@/locales";
import SvgIcon from "@/components/custom/svg-icon.vue";
import {
  getLayoutAndPage,
  getRouteNameByViewPath,
  getRoutePathByRouteName,
  normalizeViewPath,
  transformLayoutAndPageToComponent,
  type PageEntry,
} from "./shared";

defineOptions({
  name: "MenuOperateModal",
});

export type OperateType = NaiveUI.TableOperateType | "addChild";

interface Props {
  /** the type of operation */
  operateType: OperateType;
  /** the edit menu data or the parent menu data when adding a child menu */
  rowData?: Api.SystemManage.Menu | null;
  /** selectable application pages */
  allPages: PageEntry[];
}

const props = defineProps<Props>();

interface Emits {
  (e: "submitted", data: Api.SystemManage.Menu): void;
}

const emit = defineEmits<Emits>();

const visible = defineModel<boolean>("visible", {
  default: false,
});

const { formRef, validate, restoreValidation } = useNaiveForm();
const { defaultRequiredRule } = useFormRules();

const title = computed(() => {
  const titles: Record<OperateType, string> = {
    add: $t("page.manage.menu.addMenu"),
    addChild: $t("page.manage.menu.addChildMenu"),
    edit: $t("page.manage.menu.editMenu"),
  };
  return titles[props.operateType];
});

type Model = Pick<
  Api.SystemManage.Menu,
  | "menuType"
  | "menuName"
  | "routeName"
  | "routePath"
  | "component"
  | "order"
  | "i18nKey"
  | "icon"
  | "iconType"
  | "parentId"
  | "href"
  | "activeMenu"
  | "fixedIndexInTab"
> & {
  query: NonNullable<Api.SystemManage.Menu["query"]>;
  buttons: NonNullable<Api.SystemManage.Menu["buttons"]>;
  layout: string;
  page: string;
  status: Api.Common.EnableStatus;
  keepAlive: boolean;
  constant: boolean;
  hideInMenu: boolean;
  multiTab: boolean;
};

const model = ref(createDefaultModel());
const routeNameAutoGenerated = ref(true);
const routePathAutoGenerated = ref(true);

const scrollbarRef = ref<{ scrollTo: (options: { top?: number }) => void }>();

function createDefaultModel(): Model {
  return {
    menuType: "2",
    menuName: "",
    routeName: "",
    routePath: "",
    component: "",
    layout: "",
    page: "",
    i18nKey: null,
    icon: "",
    iconType: "1",
    parentId: "0",
    status: "1",
    keepAlive: false,
    constant: false,
    order: 0,
    href: null,
    hideInMenu: false,
    activeMenu: null,
    multiTab: false,
    fixedIndexInTab: null,
    query: [],
    buttons: [],
  };
}

type RuleKey = Extract<
  keyof Model,
  "menuName" | "status" | "routeName" | "routePath"
>;

const rules: Record<RuleKey, App.Global.FormRule> = {
  menuName: defaultRequiredRule,
  status: defaultRequiredRule,
  routeName: defaultRequiredRule,
  routePath: defaultRequiredRule,
};

const disabledMenuType = computed(() => props.operateType === "edit");

const localIcons = getLocalIcons();
const localIconOptions = localIcons.map<SelectOption>((item) => ({
  label: () => (
    <div class="flex-y-center gap-16px">
      <SvgIcon localIcon={item} class="text-icon" />
      <span>{item}</span>
    </div>
  ),
  value: item,
}));

const showLayout = computed(() => model.value.parentId === "0");

const showPage = computed(() => model.value.menuType === "2");

const pageOptions = computed<CommonType.Option[]>(() => {
  const options = props.allPages.map((item) => ({
    label: item.viewPath,
    value: item.viewPath,
  }));
  const selectedPage = model.value.page;

  if (selectedPage && !options.some((item) => item.value === selectedPage)) {
    options.unshift({ label: `${$t("page.manage.menu.form.legacyPage")}: ${selectedPage}`, value: selectedPage });
  }

  return options;
});

const routeNameOptions = computed<CommonType.Option[]>(() =>
  props.allPages.map((item) => ({
    label: item.routeName,
    value: item.routeName,
  })),
);

const layoutOptions: CommonType.Option[] = [
  {
    label: "base",
    value: "base",
  },
  {
    label: "blank",
    value: "blank",
  },
];

function handleInitModel() {
  model.value = createDefaultModel();
  routeNameAutoGenerated.value = props.operateType !== "edit";
  routePathAutoGenerated.value = props.operateType !== "edit";

  if (!props.rowData) return;

  if (props.operateType === "addChild") {
    const { id } = props.rowData;

    Object.assign(model.value, { parentId: id });
  }

  if (props.operateType === "edit") {
    const { component, ...rest } = props.rowData;
    const { layout, page: routeName } = getLayoutAndPage(component);
    const page = props.allPages.find((item) => item.routeName === routeName)?.viewPath || routeName;

    Object.assign(model.value, rest, {
      layout,
      page,
    });
  }

  if (!model.value.query) {
    model.value.query = [];
  }
  if (!model.value.buttons) {
    model.value.buttons = [];
  }
}

function closeDrawer() {
  visible.value = false;
}

function handleUpdateRoutePathByRouteName() {
  if (!routePathAutoGenerated.value) return;

  if (model.value.routeName) {
    model.value.routePath = getRoutePathByRouteName(model.value.routeName);
  } else {
    model.value.routePath = "";
  }
}

function handleUpdateI18nKeyByRouteName() {
  if (model.value.routeName) {
    model.value.i18nKey = `route.${model.value.routeName}` as App.I18n.I18nKey;
  } else {
    model.value.i18nKey = null;
  }
}

function getSubmitParams() {
  const { layout, page, ...params } = model.value;
  const routeName = getRouteNameByViewPath(page);

  params.component = transformLayoutAndPageToComponent(layout, routeName);

  return params;
}

function handleRouteNameInput(value: string) {
  routeNameAutoGenerated.value = false;
  model.value.routeName = value;
}

function handleRoutePathInput(value: string) {
  routePathAutoGenerated.value = false;
  model.value.routePath = value;
}

async function handleSubmit() {
  await validate();

  const params = getSubmitParams();

  if (props.operateType === "edit" && props.rowData) {
    await updateMenu({ ...params, id: props.rowData.id });
  } else {
    await addMenu(params);
  }

  window.$message?.success($t("common.modifySuccess"));
  closeDrawer();
  emit(
    "submitted",
    props.rowData
      ? ({ ...props.rowData, ...params } as Api.SystemManage.Menu)
      : (params as Api.SystemManage.Menu),
  );
}

watch(visible, () => {
  if (visible.value) {
    handleInitModel();
    restoreValidation();
    nextTick(() => scrollbarRef.value?.scrollTo({ top: 0 }));
  }
});

watch(
  () => model.value.routeName,
  () => {
    handleUpdateRoutePathByRouteName();
    handleUpdateI18nKeyByRouteName();
  },
);

// 新增时选择或录入完整视图路径后带出路由名，routeName 再联动生成 routePath 与 i18nKey。
watch(
  () => model.value.page,
  (page) => {
    if (routeNameAutoGenerated.value && props.operateType !== "edit") {
      model.value.routeName = page ? getRouteNameByViewPath(page) : "";
    }
  },
);

function handlePageChange(value: string) {
  model.value.page = normalizeViewPath(value);
}
</script>

<template>
  <NModal v-model:show="visible" :title="title" preset="card" class="w-880px max-w-[calc(100vw-32px)]">
    <NScrollbar ref="scrollbarRef" class="h-560px pr-16px">
      <NForm ref="formRef" :model="model" :rules="rules" label-placement="left" :label-width="96">
        <NDivider title-placement="left">{{ $t('page.manage.menu.section.basic') }}</NDivider>
        <NGrid responsive="screen" item-responsive :x-gap="16" :y-gap="12">
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.menuType')" path="menuType">
            <NRadioGroup v-model:value="model.menuType" :disabled="disabledMenuType">
              <NRadio v-for="item in menuTypeOptions" :key="item.value" :value="item.value" :label="$t(item.label)" />
            </NRadioGroup>
          </NFormItemGi>
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.menuName')" path="menuName">
            <NInput v-model:value="model.menuName" :placeholder="$t('page.manage.menu.form.menuName')" />
          </NFormItemGi>
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.routeName')" path="routeName">
            <NInput
              :value="model.routeName"
              :placeholder="$t('page.manage.menu.form.routeName')"
              @update:value="handleRouteNameInput"
            />
          </NFormItemGi>
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.routePath')" path="routePath">
            <NInput
              :value="model.routePath"
              :placeholder="$t('page.manage.menu.form.routePath')"
              @update:value="handleRoutePathInput"
            />
          </NFormItemGi>
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.order')" path="order">
            <NInputNumber v-model:value="model.order" class="w-full" :placeholder="$t('page.manage.menu.form.order')" />
          </NFormItemGi>
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.menuStatus')" path="status">
            <NSwitch v-model:value="model.status" checked-value="1" unchecked-value="2" />
          </NFormItemGi>
        </NGrid>

        <NDivider title-placement="left">{{ $t('page.manage.menu.section.page') }}</NDivider>
        <NGrid responsive="screen" item-responsive :x-gap="16" :y-gap="12">
          <NFormItemGi v-if="showLayout" span="24 m:12" :label="$t('page.manage.menu.layout')" path="layout">
            <NSelect
              v-model:value="model.layout"
              :options="layoutOptions"
              :placeholder="$t('page.manage.menu.form.layout')"
            />
          </NFormItemGi>
          <NFormItemGi v-if="showPage" span="24 m:12" :label="$t('page.manage.menu.page')" path="page">
            <NSelect
              :value="model.page"
              :options="pageOptions"
              :placeholder="$t('page.manage.menu.form.page')"
              filterable
              tag
              @update:value="handlePageChange"
            />
          </NFormItemGi>
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.i18nKey')" path="i18nKey">
            <NInput v-model:value="model.i18nKey" :placeholder="$t('page.manage.menu.form.i18nKey')" />
          </NFormItemGi>
        </NGrid>

        <NDivider title-placement="left">{{ $t('page.manage.menu.section.display') }}</NDivider>
        <NGrid responsive="screen" item-responsive :x-gap="16" :y-gap="12">
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.iconTypeTitle')" path="iconType">
            <NRadioGroup v-model:value="model.iconType">
              <NRadio
                v-for="item in menuIconTypeOptions"
                :key="item.value"
                :value="item.value"
                :label="$t(item.label)"
              />
            </NRadioGroup>
          </NFormItemGi>
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.icon')" path="icon">
            <template v-if="model.iconType === '1'">
              <NInput v-model:value="model.icon" :placeholder="$t('page.manage.menu.form.icon')" class="flex-1">
                <template #suffix>
                  <SvgIcon v-if="model.icon" :icon="model.icon" class="text-icon" />
                </template>
              </NInput>
            </template>
            <template v-if="model.iconType === '2'">
              <NSelect
                v-model:value="model.icon"
                :placeholder="$t('page.manage.menu.form.localIcon')"
                :options="localIconOptions"
              />
            </template>
          </NFormItemGi>
          <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.href')" path="href">
            <NInput v-model:value="model.href" :placeholder="$t('page.manage.menu.form.href')" />
          </NFormItemGi>
        </NGrid>

        <NCollapse class="mt-16px">
          <NCollapseItem name="advanced">
            <template #header>
              <div>
                <div class="font-600">{{ $t('page.manage.menu.section.advanced') }}</div>
                <div class="mt-2px text-12px text-gray-5">{{ $t('page.manage.menu.form.advancedHint') }}</div>
              </div>
            </template>
            <div class="pb-4px pt-12px">
              <NGrid responsive="screen" item-responsive :x-gap="16" :y-gap="12">
                <NFormItemGi v-if="showPage" span="24 m:12" :label="$t('page.manage.menu.keepAlive')" path="keepAlive">
                  <NSwitch v-model:value="model.keepAlive" />
                </NFormItemGi>
                <NFormItemGi span="24 m:12" :label="$t('page.manage.menu.hideInMenu')" path="hideInMenu">
                  <NSwitch v-model:value="model.hideInMenu" />
                </NFormItemGi>
                <NFormItemGi
                  v-if="showPage && model.hideInMenu"
                  span="24 m:12"
                  :label="$t('page.manage.menu.activeMenu')"
                  path="activeMenu"
                >
                  <NSelect
                    v-model:value="model.activeMenu"
                    :options="routeNameOptions"
                    clearable
                    :placeholder="$t('page.manage.menu.form.activeMenu')"
                  />
                </NFormItemGi>
                <NFormItemGi v-if="showPage" span="24 m:12" :label="$t('page.manage.menu.multiTab')" path="multiTab">
                  <NSwitch v-model:value="model.multiTab" />
                </NFormItemGi>
              </NGrid>

              <div v-if="showPage" class="mt-8px">
                <div class="mb-8px text-14px font-500">{{ $t('page.manage.menu.query') }}</div>
                <div class="mb-12px text-12px leading-20px text-gray-5">
                  {{ $t('page.manage.menu.form.queryHint') }}
                </div>
                <NDynamicInput
                  v-model:value="model.query"
                  preset="pair"
                  :key-placeholder="$t('page.manage.menu.form.queryKey')"
                  :value-placeholder="$t('page.manage.menu.form.queryValue')"
                >
                  <template #action="{ index, create, remove }">
                    <NSpace class="ml-12px" :wrap="false">
                      <NButton size="medium" @click="() => create(index)">
                        <icon-ic-round-plus class="text-icon" />
                      </NButton>
                      <NButton size="medium" @click="() => remove(index)">
                        <icon-ic-round-remove class="text-icon" />
                      </NButton>
                    </NSpace>
                  </template>
                </NDynamicInput>
              </div>
            </div>
          </NCollapseItem>
        </NCollapse>
      </NForm>
    </NScrollbar>
    <template #footer>
      <NSpace justify="end" :size="16">
        <NButton @click="closeDrawer">{{ $t('common.cancel') }}</NButton>
        <NButton type="primary" @click="handleSubmit">{{ $t('common.confirm') }}</NButton>
      </NSpace>
    </template>
  </NModal>
</template>

<style scoped></style>
